name: Update progress

on:
  push:
    branches:
      - master
    paths:
      - 'src/*.c'
      - 'src/**/*.c'
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v2
      - name: Clone asset repository
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Generate report
        run: |
            mkdir -p gh-pages/assets
            python tools/report_progress.py DRA.BIN 630 src/dra > gh-pages/assets/progress-dra.json
            python tools/report_progress.py RIC.BIN 155 src/ric > gh-pages/assets/progress-ric.json
            python tools/report_progress.py DRE.BIN 136 src/st/dre > gh-pages/assets/progress-dre.json
            python tools/report_progress.py MAD.BIN 116 src/st/mad > gh-pages/assets/progress-mad.json
            python tools/report_progress.py NO3.BIN 210 src/st/no3 > gh-pages/assets/progress-no3.json
            python tools/report_progress.py NP3.BIN 214 src/st/np3 > gh-pages/assets/progress-np3.json
            python tools/report_progress.py ST0.BIN 160 src/st/st0 > gh-pages/assets/progress-st0.json
            python tools/report_progress.py WRP.BIN 110 src/st/wrp > gh-pages/assets/progress-wrp.json
            python tools/report_progress.py RWRP.BIN 110 src/st/rwrp > gh-pages/assets/progress-rwrp.json
      - name: Commit report
        run: |
            git config --global user.name 'GitHub Action' 
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m 'Update progress' || true
            git push
        working-directory: gh-pages
